#!/usr/bin/env bash

depend wmctrl tail cut grep zenity firefox || exit

function get_current_desktop() {
	current_desktop=$(wmctrl -d | grep "*" | cut -f1 -d " ")
	echo "current_desktop = $current_desktop"
}

function get_instances() {
	if [[ -n "$PRIVATE" ]]; then
		wmctrl -l | grep -ve 'Firefox$' | grep -e 'Firefox'
	else
		wmctrl -l | grep -e 'Firefox$'
	fi
}

function get_latest_instance() {
	latest_instance=$(get_instances | tail -n1 | cut -f1 -d' ')
	echo "current_instance = $latest_instance"
}

function has_any_instance() {
	[[ -n "$current_instance" ]] || get_instances > /dev/null
}

function get_current_instance() {
	current_instance=$(get_instances | grep -e " $current_desktop" | tail -n1 | cut -f1 -d' ')
	echo "current_instance = $current_instance"
}

CHOICES=$(
	zenity --list --checklist --text="$1" --separator='\n' \
	--column '' --column 'Open in' \
	FALSE 'New window' \
	TRUE 'This workspace' \
	TRUE 'Private mode'
) || exit 0

while read -r CHOICE; do
	case "$CHOICE" in
		'New window')
			NEW=1
			;;
		'Private mode')
			PRIVATE=1
			;;
		'This workspace')
			THISWS=1
			;;
	esac
done <<< "$CHOICES"

get_current_desktop
sleep 0.1
get_current_instance

if [[ -n "$PRIVATE" ]]; then
	if [[ -n "$THISWS" ]] && has_any_instance && [[ -z "$current_instance" ]] || [[ -z "$1" ]]; then
		NEW=1
	fi

	if [[ -n "$NEW" ]]; then
		firefox -private-window

		sleep 0.4
		timeout=20
		while [[ -z "$current_instance" ]] && (( timeout > 0 )); do
			sleep 0.4
			get_current_instance
			timeout=$((timeout-1))
		done
	fi

	if [[ -n "${1+x}" ]]; then
		firefox -private-window "$1"
	fi
else
	if [[ -n "$THISWS" ]] && [[ -z $current_instance ]]; then
		NEW=1
	fi

	if [[ -n "$NEW" ]]; then
		firefox -new-window ${1+"$1"}
	else
		firefox ${1+"$1"}
	fi
fi

get_latest_instance

if [[ -n "$NEW" ]]; then
	wmctrl -i -r "$latest_instance" -b add,maximized_vert
	wmctrl -i -r "$latest_instance" -b add,maximized_horz
else
	wmctrl -i -a "$latest_instance"
fi