#!/usr/bin/env bash

function get_current_desktop() {
	current_desktop=$(wmctrl -d | grep "*" | cut -f1 -d " ")
	echo "current_desktop = $current_desktop"
}

function get_current_instance_normal() {
	current_instance=$(wmctrl -lx | grep -e " $current_desktop" | grep -e 'Firefox$' | head -n1 | cut -f1 -d' ')
	echo "current_instance = $current_instance"
}
function get_current_instance_private() {
	current_instance=$(wmctrl -lx | grep -e " $current_desktop" | grep -ve 'Firefox$' | grep -e 'Firefox' | head -n1 | cut -f1 -d' ')
	echo "current_instance = $current_instance"
}
function has_any_instance_private() {
	wmctrl -lx | grep -ve 'Firefox$' | grep -qe 'Firefox'
}
function get_current_instance() {
	if [[ -n "$PRIVATE" ]]; then
		get_current_instance_private
	else
		get_current_instance_normal
	fi
}

CHOICES=$(
	zenity --list --checklist --text="$1" --separator='\n' \
	--column '' --column 'Open in' \
	FALSE 'New window' \
	TRUE 'This workspace' \
	TRUE 'Private mode'
) || exit 0

while read -r CHOICE; do
	case "$CHOICE" in
		'New window')
			NEW=1
			;;
		'Private mode')
			PRIVATE=1
			;;
		'This workspace')
			THISWS=1
			;;
	esac
done <<< "$CHOICES"

get_current_desktop
sleep 0.1
get_current_instance

if [[ -n "$PRIVATE" ]]; then
	if [[ -n "$THISWS" ]] && has_any_instance_private && [[ -z "$current_instance" ]]; then
		NEW=1
	fi

	if [[ -n "$NEW" ]]; then
		firefox -private-window

		timeout=20
		while [[ -z "$current_instance" ]] && (( timeout > 0 )); do
			sleep 0.4
			get_current_instance
			timeout=$((timeout-1))
		done
	fi

	if [[ -n "${1+x}" ]]; then
		sleep 0.2
		firefox -private-window "$1"
	fi
else
	if [[ -n "$THISWS" ]] && [[ -z $current_instance ]]; then
		NEW=1
	fi

	if [[ -n "$NEW" ]]; then
		firefox -new-window ${1+"$1"} &
	else
		firefox -foreground ${1+"$1"} &
	fi
fi

[[ -n "$THISWS" ]] || exit 0

timeout=20
while [[ -z "$current_instance" ]] && (( timeout > 0 )); do
	get_current_instance
	timeout=$((timeout-1))
	sleep 0.1
done

(( timeout > 0 )) || exit

wmctrl -i -r "$current_instance" -b add,maximized_vert
wmctrl -i -r "$current_instance" -b add,maximized_horz
