#!/usr/bin/env bash

depend wine winepath zenity find readlink xargs || exit

# TODO support goldsrc
GAMEDIR=$(
	while ! [[ -e ./bin/hlmv.exe ]] && ! [[ "$(pwd)" = / ]]; do
		cd .. || break
	done
	pwd -P
)

if ! [[ -e "$GAMEDIR"/bin/hlmv.exe ]]; then
	GAMEDIR="$(
		grep path "$HOME"/.steam/steam/config/libraryfolders.vdf |
		sed 's,^.*path\(\"\|\)\s*,,; s,\s*$,,' | tr -d \" |
		xargs -I{} find "{}/steamapps/common" -path '*/bin/hlmv.exe' -printf '%p\0%P\0' |
		xargs -0 zenity --list --column=_ --column=HLMV --hide-column=1 --text='Select HLMV variant'
	)"
	
	GAMEDIR=$(readlink -f "$GAMEDIR")
	GAMEDIR="${GAMEDIR%/bin/hlmv.exe}"
	
	mapfile -t MODDIRS < <(
		cd "$GAMEDIR" || exit
		for f in *; do
			if [[ -e "$f"/gameinfo.txt ]]; then
				echo "$f"
			fi
		done
	)

	case "${#MODDIRS[@]}" in
		0) exit;;
		1) MODDIR="${MODDIRS[0]}";;
		*) MODDIR=$(xargs zenity --list --column=Directory --text='Select mod directory' <<< "${MODDIRS[@]}");;
	esac

	[[ -n "$MODDIR" ]] || exit
	export VPROJECT="${VPROJECT-"$GAMEDIR/$MODDIR"}"
fi

ARGS=()
while (( $# > 0 )); do
	if [[ -e "$1" ]]; then
		ARGS+=("$(winepath -w "$1")")
	else
		ARGS+=("$1")
	fi
	shift
done

exec wine "${GAMEDIR?}"/bin/hlmv.exe "${ARGS[@]}"