#!/usr/bin/env bash
INNAME="${1:?}"
OUTNAME="${2}"
: "${OUTNAME:="${INNAME%.md}.pdf"}"
depend mdhtml pandoc || exit
echo "Converting ${INNAME##*/} -> ${OUTNAME##*/}"

mdhtml "$INNAME" - "${@:3}" | pandoc - -o "$OUTNAME" -f html -t latex -s\
 --pdf-engine=latexmk --pdf-engine-opt=-lualatex\
 -V 'documentclass=scrartcl' \
 --metadata-file=<(cat <<-EOF
	geometry:
	  - left=1cm
	  - right=1cm
	  - top=1cm
	  - bottom=1cm
	  - includehead
	  - includefoot
	fontsize: 12pt
	mainfont: DejaVu Serif
	sansfont: DejaVu Sans
	monofont: DejaVu Sans Mono
	mathfont: DejaVu Math TeX Gyre
	mainfontfallback: 
	  - "FreeSerif:"
	  - "NotoColorEmoji:mode=harf"
#	mainfont: FreeSerif
#	sansfont: FreeSans
#	monofont: FreeMono
#	mathfont: Asana Math
#	mainfontfallback: 
#	  - "NotoColorEmoji:mode=harf"
EOF
)
