#!/usr/bin/env bash

depend inotifywait vpkedit mkdir pgrep grep hlmv xdg-open readlink cat ps pkill || exit

LANDDIR="${XDG_CACHE_HOME:-$HOME/.cache}/0_VPKEDIT_PREVIEW"
PIDFILE="${XDG_RUNTIME_DIR?}/vpkedit-preview.pid"

set -m

(
	if [[ -e "$PIDFILE" ]] && ps -p "$(cat "$PIDFILE")"; then
		exit
	fi

	echo "$BASHPID" > "$PIDFILE"

	TMPDIR=$(mktemp -d --tmpdir="${XDG_RUNTIME_DIR?}" vpkeditw-XXXX)
	mkdir "$LANDDIR"
	trap 'rm -r "$LANDDIR" "$TMPDIR"; pkill -g0 inotifywait' EXIT

	while read -r FILE; do
		[[ -e "$LANDDIR/$FILE" ]] || continue
		mv -ft "$TMPDIR" "$LANDDIR/$FILE"

		case "$FILE" in
			(*.vtx|*.vvd|*.phy|*.ani);;
			(*.mdl)
				hlmv "$TMPDIR/$FILE" &
				;;
			(*)
				xdg-open "$TMPDIR/$FILE" &
				;;
		esac
	done < <(inotifywait -qm -e close_write --format %f "$LANDDIR")
) &

trap 'pgrep -l vpkedit | grep -qv vpkeditw || kill "$(cat "$PIDFILE")"' EXIT

vpkedit "$(readlink -f "$1")"