#!/usr/bin/env bash

depend inotifywait vpkedit mkdir pgrep grep hlmv xdg-open readlink

LANDDIR="${XDG_CACHE_HOME:-$HOME/.cache}/0_VPKEDIT_PREVIEW"

(
	if [[ -d "$LANDDIR" ]]; then
		exit
	fi

	TMPDIR=$(mktemp -d --tmpdir"${XDG_RUNTIME_DIR:+=$XDG_RUNTIME_DIR}" vpkeditw-XXXX)
	mkdir "$LANDDIR"
	trap 'rm -r "$LANDDIR"; rm -r "$TMPDIR"' EXIT

	while true; do
		inotifywait -qm -t5 -e close_write --format %f "$LANDDIR" |
		while read -r FILE; do
			[[ -e "$LANDDIR/$FILE" ]] || continue
			mv -ft "$TMPDIR" "$LANDDIR/$FILE"

			case "$FILE" in
				(*.vtx|*.vvd|*.phy|*.ani);;
				(*.mdl)
					hlmv "$TMPDIR/$FILE" &
					;;
				(*)
					xdg-open "$TMPDIR/$FILE" &
					;;
			esac
		done

		if ! pgrep vpkedit; then
			break
		fi
	done
) &

exec vpkedit "$(readlink -f "$1")"