#!/usr/bin/env bash

DIR=$(mktemp -d -t "${0##*/}-$$"-ytdl-XXXXX)
QUEUE2="$DIR"/queue2
INFODIR="$DIR"/info

cleanup() {
	rm -r "$DIR"
}

trap 'cleanup' EXIT

xclip -i -selection clipboard < /dev/null
mkdir "$INFODIR"

trap 'break' SIGINT

echo 'Copy URLs to add them, ^C to finish'

counter=1
prev=$(xclip -selection clipboard -o)
while true; do
	curr=$(xclip -selection clipboard -o)
	if [[ "$curr" != "$prev" ]]; then
		echo "Copied $curr"
		yt-dlp -P "$INFODIR" --print-to-file '%()j' "$INFODIR"/dl"$counter".info.json -f 'w*' --print 'Added %(title)s' "$curr" &
		prev="$curr"
		counter=$((counter+1))
	fi
	sleep 0.2
done

trap - SIGINT

wait

if [[ -z "$(ls -A "$INFODIR")" ]]; then
	echo "Nothing to download"
	exit
fi

for f in "$INFODIR"/*; do
	printf '%*s\n' "$(tput cols)" | tr ' ' '-'
	yt-dlp -f 'w*' --no-sponsorblock --load-info-json "$f" --print "Select format for %(title)s"
	yt-dlp -sf - --no-sponsorblock --print-to-file "%(format_id)s $f" "$QUEUE2" --load-info-json "$f"
done

while read -r format info; do
	yt-dlp --load-info-json "$info" -f "$format"
done < "$QUEUE2"
