#!/usr/bin/env bash

DIR=$(mktemp -d -t "${0##*/}-$$"-ytdl-XXXXX)
QUEUE2="$DIR"/queue2
INFODIR="$DIR"/info

cleanup() {
	jobs -pr | xargs -r kill
	rm -r "$DIR"
}

trap 'cleanup' EXIT

while getopts 'f:F' OPT; do
	case "$OPT" in
		'f')
			FORMAT="$OPTARG"
			;;
		'F')
			FORMAT='-'
			;;
		*);;
	esac
done

xclip -i -selection clipboard < /dev/null
mkdir "$INFODIR"

echo 'Copy URLs to add them -- [F] finish, [C] clear, [Q] quit'

counter=1
prev=$(xclip -selection clipboard -o)
while true; do
	curr=$(xclip -selection clipboard -o)
	if [[ "$curr" != "$prev" ]]; then
		echo "Copied $curr"
		yt-dlp -P "$INFODIR" --print-to-file '%()j' dl"$counter"'%(autonumber)s'.info.json -f 'w*' --print 'Added %(title)s' "$curr" &
		prev="$curr"
		counter=$((counter+1))
	fi

	read -st0.2 -N1 input
	case "$input" in
		'f'|'F') break;;
		'c'|'C') rm "$INFODIR"/*; counter=1; echo 'Cleared';;
		'q'|'Q') exit 0;;
	esac
done

wait

if [[ -z "$(ls -A "$INFODIR")" ]]; then
	echo "Nothing to download"
	exit
fi

for f in "$INFODIR"/*; do
	printf '%*s\n' "$(tput cols)" | tr ' ' '-'
	yt-dlp -f 'w*' --no-sponsorblock --load-info-json "$f" --print "Selecting format for %(title)s"
	if ! yt-dlp -s ${FORMAT+-f "$FORMAT"} --no-sponsorblock --print-to-file "%(format_id)s $f %(title)S" "$QUEUE2" --load-info-json "$f"; then
		yt-dlp -sf- --no-sponsorblock --print-to-file "%(format_id)s $f %(title)S" "$QUEUE2" --load-info-json "$f"
	fi
done

[[ -r "$QUEUE2" ]] || exit

while read -r format info title; do
	yt-dlp --load-info-json "$info" -f "$format" --newline --progress-delta 5 --color always | sed "s,^,[$title]\n," &

	while (( $(jobs -pr | wc -l) >= 2)); do
		wait -n
	done
done < "$QUEUE2"

wait