#!/usr/bin/env bash

depend mktemp mkdir xargs xclip yt-dlp || exit

DIR=$(mktemp -d -t "${0##*/}-$$"-ytdl-XXXXX)
QUEUE2="$DIR"/queue2
INFODIR="$DIR"/info
FAILQUEUE="$DIR"/fail_queue

cleanup() {
	jobs -pr | xargs -r kill
	rm -r "$DIR"
}

trap 'cleanup' EXIT

while getopts 'f:F' OPT; do
	case "$OPT" in
		'f')
			FORMAT="$OPTARG"
			;;
		'F')
			FORMAT='-'
			;;
		*);;
	esac
done

xclip -i -selection clipboard < /dev/null
mkdir "$INFODIR"

echo 'Copy URLs to add them -- [F] finish, [C] clear, [Q] quit'

counter=1
prev=$(xclip -selection clipboard -o)
while true; do
	curr=$(xclip -selection clipboard -o)
	if [[ "$curr" != "$prev" ]]; then
		echo "Copied $curr"
		yt-dlp -P "$INFODIR" --print-to-file '%()j' dl"$counter"'%(autonumber)s'.info.json -f 'w*' --print 'Added %(title)s' "$curr" &
		prev="$curr"
		counter=$((counter+1))
	fi

	read -srt0.2 -N1 input
	case "$input" in
		'f'|'F') break;;
		'c'|'C') rm "$INFODIR"/*; counter=1; echo 'Cleared';;
		'q'|'Q') exit 0;;
	esac
done

wait

if [[ -z "$(ls -A "$INFODIR")" ]]; then
	echo "Nothing to download"
	exit
fi

for f in "$INFODIR"/*; do
	printf '%*s\n' "$(tput cols)" '' | tr ' ' '_'
	yt-dlp -f 'w*' --no-sponsorblock --load-info-json "$f" --print "Selecting format for %(title)s"
	if ! yt-dlp -s ${FORMAT+-f "$FORMAT"} --no-sponsorblock --print-to-file "%(format_id)s $f" "$QUEUE2" --load-info-json "$f"; then
		yt-dlp -sf- --no-sponsorblock --print-to-file "%(format_id)s $f" "$QUEUE2" --load-info-json "$f"
	fi
done

[[ -r "$QUEUE2" ]] || exit

while true; do
	clear -x

	unset LINE_BUSY
	declare -A LINE_BUSY
	unset PID_LINE
	declare -A PID_LINE
	unset FINISHED
	declare -a FINISHED
	max_line=1

	while read -r format info; do
		line=1
		while [[ -n "${LINE_BUSY[$line]}" ]]; do
			line=$((line+2))
			if ((line > max_line)); then
				max_line=$line
			fi
			if ((line+2 >= $(tput lines))); then
				for pid in "${FINISHED[@]}"; do
					unset "LINE_BUSY[${PID_LINE[$pid]}]"
					unset "PID_LINE[$pid]"
				done
			fi
		done

		logfile=$(yt-dlp --load-info-json "$info" --no-sponsorblock --print filename)
		logfile=${logfile%.*}.log

		printf '\033[%d;H\033[2K%s' "$line" "$(yt-dlp --load-info-json "$info" --no-sponsorblock --print "%(title)s -- $format")"

		(
			set -eo pipefail
			if yt-dlp --load-info-json "$info" -f "$format" \
				--newline --progress --progress-delta 1 --color always \
				--no-simulate --print "Starting download for %(id)s" --print "after_move:%(id)s done" \
				--quiet --verbose 2> "$logfile" && [ "$(shuf -i 0-1 -n1)" == 0 ]
			then
				rm "$logfile"
				sleep 1
				exit 0
			else
				echo Failed
				echo "$format" "$info" >> "$FAILQUEUE"
				sleep 1
				exit 1
			fi | xargs -L1 echo -ne "\033[$((line+1));H\033[2K"
		) &
		PID_LINE[$!]=$line
		LINE_BUSY[$line]=1

		while (( $(jobs -pr | wc -l) >= 2)); do
			if wait -np pid; then
				unset "LINE_BUSY[${PID_LINE[$pid]}]"
				unset "PID_LINE[$pid]"
			fi
			FINISHED+=("$pid")
		done
		sleep 0.1
	done < "$QUEUE2"

	wait

	printf '\033[%d;H' "$((max_line+2))"

	if [[ -r "$FAILQUEUE" ]] && (( $(wc -l < "$FAILQUEUE") > 0 )) && read -rN1 -p "$(wc -l < "$FAILQUEUE") failed, retry?"; then
		case "$REPLY" in
			y|Y) mv -f "$FAILQUEUE" "$QUEUE2"; continue;;
			*);;
		esac
	fi
	break
done