#!/usr/bin/env bash

depend mktemp dirname mv rm sed yt-dlp ffmpeg /opt/ytsubconverter/ytsubconverter

if (( "$#" < 1)); then
	>&2 echo "Usage: ${0##*/} <ID> [<language> [format]]"
	exit
fi

if (( "$#" < 2 )); then
	yt-dlp --no-warnings --no-write-subs --no-write-auto-subs --skip-download --list-subs "$1"
else
	DIR=$(mktemp -d)
	FMT="${3+$3/}best"
	FMT="$(sed 's,ass\|srv3\|ytt,ass/srv3/ytt,' <<< "$FMT")"
	
	yt-dlp -P "$DIR" --no-warnings --skip-download --write-subs --write-auto-subs --sub-format "$FMT" --sub-langs "$2" "$1"
	if (( "$#" >= 3 )); then
		for sub in "$DIR"/*; do
			if [[ "${sub##*.}" != "$3" ]]; then
				case "${sub##*.}__$3" in
					'srv3__ass'|'srv3__ytt'|'ass__srv3'|'ass__ytt'|'ytt__ass'|'ytt__srv3')
						/opt/ytsubconverter/ytsubconverter "$sub" "${sub%.*}.$3" && rm "$sub"
						;;
					'srv3__'*)
						/opt/ytsubconverter/ytsubconverter "$sub" "$DIR/__temp.ass"
						ffmpeg -hide_banner -i "$DIR/__temp.ass" -f "$3" "${sub%.*}.$3" && rm "$sub"
						rm "$DIR/__temp.ass"
						;;
					*)
						ffmpeg -hide_banner -i "$sub" -f "$3" "${sub%.*}.$3" && rm "$sub"
						;;
				esac
			else
				echo "File ignored: $sub"
			fi
		done
	fi
	mv "$DIR"/* "$(dirname "$(yt-dlp --print filename "$1")")"
	rm -r "$DIR"
fi
