#!/usr/bin/env bash

if (( "$#" < 2 )); then
	yt-dlp --no-warnings --skip-download --list-subs "$1"
else
	yt-dlp --no-warnings --skip-download --write-subs --write-auto-subs --sub-langs "$2" "$1"
	if (( "$#" >= 3 )); then
		FILENAME=$(yt-dlp --no-warnings --get-filename "$1")
		FILENAME="${FILENAME%.*}"
		for sub in "$FILENAME."*; do
			if [[ "${sub##*.}" != "$3" ]] && ! ffprobe -hide_banner -show_entries stream=codec_type "$sub" 2> /dev/null | egrep '(audio|video)' > /dev/null; then
				ffmpeg -hide_banner -i "$sub" -f "$3" "${sub%.*}.$3"
				rm "$sub"
			else
				echo "File ignored: $sub"
			fi
		done
	fi
fi

#import yt_dlp
#import sys
#
#if len(sys.argv) < 3:
#	opt = {'skip_download': True, 'listsubtitles': True}
#else:
#	opt = {
#		'writesubtitles': True,
#		'writeautomaticsub': True,
#		'skip_download': True,
#		'subtitleslangs': sys.argv[2].split(','),
#		'verbose': True
#	}
#	if len(sys.argv) >= 4:
#		opt['subtitlesformat'] = sys.argv[3] POSTPROCESS_WHEN = ('pre_process', 'after_filter', 'video', 'before_dl', 'post_process', 'after_move', 'after_video', 'playlist')
#		opt['postprocessors'] = [{'key': 'FFmpegSubtitlesConvertor', 'format': sys.argv[3], 'when': 'after_video'}]
#
#with yt_dlp.YoutubeDL(opt) as ytdl:
#	ytdl.download(sys.argv[1])
